// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentinterfaces.proxies;

/**
 * Transactions for iPay88. All iPay88 related actions will generate an IPay88Transaction Object. If the current transaction is not found when the user is redirected from iPay88, a new object is created for registration purposes.
 */
public class IPay88Transaction
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject iPay88TransactionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentInterfaces.IPay88Transaction";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		iPayTransactionID("iPayTransactionID"),
		Req_MerchantKey("Req_MerchantKey"),
		Req_MerchantCode("Req_MerchantCode"),
		Req_PaymentId("Req_PaymentId"),
		Req_RefNo("Req_RefNo"),
		Req_Amount("Req_Amount"),
		Req_AmountMobile("Req_AmountMobile"),
		Req_Currency("Req_Currency"),
		Req_ProdDesc("Req_ProdDesc"),
		Req_UserName("Req_UserName"),
		Req_UserEmail("Req_UserEmail"),
		Req_UserContact("Req_UserContact"),
		Req_Remark("Req_Remark"),
		Req_Lang("Req_Lang"),
		Req_Signature("Req_Signature"),
		Req_ResponseURL("Req_ResponseURL"),
		Req_BackendURL("Req_BackendURL"),
		Res_MerchantCode("Res_MerchantCode"),
		Res_PaymentId("Res_PaymentId"),
		Res_RefNo("Res_RefNo"),
		Res_Amount("Res_Amount"),
		Res_Currency("Res_Currency"),
		Res_Remark("Res_Remark"),
		Res_TransId("Res_TransId"),
		Res_AuthCode("Res_AuthCode"),
		Res_Status("Res_Status"),
		Res_ErrDesc("Res_ErrDesc"),
		Res_Signature("Res_Signature"),
		PaymentResponseStatus("PaymentResponseStatus"),
		IsCallbackProcessed("IsCallbackProcessed"),
		IPay88Transaction_PaymentRedirect("PaymentInterfaces.IPay88Transaction_PaymentRedirect");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IPay88Transaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PaymentInterfaces.IPay88Transaction"));
	}

	protected IPay88Transaction(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject iPay88TransactionMendixObject)
	{
		if (iPay88TransactionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PaymentInterfaces.IPay88Transaction", iPay88TransactionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PaymentInterfaces.IPay88Transaction");

		this.iPay88TransactionMendixObject = iPay88TransactionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'IPay88Transaction.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static paymentinterfaces.proxies.IPay88Transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentinterfaces.proxies.IPay88Transaction.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static paymentinterfaces.proxies.IPay88Transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentinterfaces.proxies.IPay88Transaction(context, mendixObject);
	}

	public static paymentinterfaces.proxies.IPay88Transaction load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentinterfaces.proxies.IPay88Transaction.initialize(context, mendixObject);
	}

	public static java.util.List<paymentinterfaces.proxies.IPay88Transaction> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<paymentinterfaces.proxies.IPay88Transaction> result = new java.util.ArrayList<paymentinterfaces.proxies.IPay88Transaction>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PaymentInterfaces.IPay88Transaction" + xpathConstraint))
			result.add(paymentinterfaces.proxies.IPay88Transaction.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of iPayTransactionID
	 */
	public final java.lang.Long getiPayTransactionID()
	{
		return getiPayTransactionID(getContext());
	}

	/**
	 * @param context
	 * @return value of iPayTransactionID
	 */
	public final java.lang.Long getiPayTransactionID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.iPayTransactionID.toString());
	}

	/**
	 * Set value of iPayTransactionID
	 * @param ipaytransactionid
	 */
	public final void setiPayTransactionID(java.lang.Long ipaytransactionid)
	{
		setiPayTransactionID(getContext(), ipaytransactionid);
	}

	/**
	 * Set value of iPayTransactionID
	 * @param context
	 * @param ipaytransactionid
	 */
	public final void setiPayTransactionID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long ipaytransactionid)
	{
		getMendixObject().setValue(context, MemberNames.iPayTransactionID.toString(), ipaytransactionid);
	}

	/**
	 * @return value of Req_MerchantKey
	 */
	public final java.lang.String getReq_MerchantKey()
	{
		return getReq_MerchantKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_MerchantKey
	 */
	public final java.lang.String getReq_MerchantKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_MerchantKey.toString());
	}

	/**
	 * Set value of Req_MerchantKey
	 * @param req_merchantkey
	 */
	public final void setReq_MerchantKey(java.lang.String req_merchantkey)
	{
		setReq_MerchantKey(getContext(), req_merchantkey);
	}

	/**
	 * Set value of Req_MerchantKey
	 * @param context
	 * @param req_merchantkey
	 */
	public final void setReq_MerchantKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_merchantkey)
	{
		getMendixObject().setValue(context, MemberNames.Req_MerchantKey.toString(), req_merchantkey);
	}

	/**
	 * @return value of Req_MerchantCode
	 */
	public final java.lang.String getReq_MerchantCode()
	{
		return getReq_MerchantCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_MerchantCode
	 */
	public final java.lang.String getReq_MerchantCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_MerchantCode.toString());
	}

	/**
	 * Set value of Req_MerchantCode
	 * @param req_merchantcode
	 */
	public final void setReq_MerchantCode(java.lang.String req_merchantcode)
	{
		setReq_MerchantCode(getContext(), req_merchantcode);
	}

	/**
	 * Set value of Req_MerchantCode
	 * @param context
	 * @param req_merchantcode
	 */
	public final void setReq_MerchantCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_merchantcode)
	{
		getMendixObject().setValue(context, MemberNames.Req_MerchantCode.toString(), req_merchantcode);
	}

	/**
	 * @return value of Req_PaymentId
	 */
	public final java.lang.String getReq_PaymentId()
	{
		return getReq_PaymentId(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_PaymentId
	 */
	public final java.lang.String getReq_PaymentId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_PaymentId.toString());
	}

	/**
	 * Set value of Req_PaymentId
	 * @param req_paymentid
	 */
	public final void setReq_PaymentId(java.lang.String req_paymentid)
	{
		setReq_PaymentId(getContext(), req_paymentid);
	}

	/**
	 * Set value of Req_PaymentId
	 * @param context
	 * @param req_paymentid
	 */
	public final void setReq_PaymentId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_paymentid)
	{
		getMendixObject().setValue(context, MemberNames.Req_PaymentId.toString(), req_paymentid);
	}

	/**
	 * @return value of Req_RefNo
	 */
	public final java.lang.String getReq_RefNo()
	{
		return getReq_RefNo(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_RefNo
	 */
	public final java.lang.String getReq_RefNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_RefNo.toString());
	}

	/**
	 * Set value of Req_RefNo
	 * @param req_refno
	 */
	public final void setReq_RefNo(java.lang.String req_refno)
	{
		setReq_RefNo(getContext(), req_refno);
	}

	/**
	 * Set value of Req_RefNo
	 * @param context
	 * @param req_refno
	 */
	public final void setReq_RefNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_refno)
	{
		getMendixObject().setValue(context, MemberNames.Req_RefNo.toString(), req_refno);
	}

	/**
	 * @return value of Req_Amount
	 */
	public final java.lang.String getReq_Amount()
	{
		return getReq_Amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_Amount
	 */
	public final java.lang.String getReq_Amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_Amount.toString());
	}

	/**
	 * Set value of Req_Amount
	 * @param req_amount
	 */
	public final void setReq_Amount(java.lang.String req_amount)
	{
		setReq_Amount(getContext(), req_amount);
	}

	/**
	 * Set value of Req_Amount
	 * @param context
	 * @param req_amount
	 */
	public final void setReq_Amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_amount)
	{
		getMendixObject().setValue(context, MemberNames.Req_Amount.toString(), req_amount);
	}

	/**
	 * @return value of Req_AmountMobile
	 */
	public final java.lang.Integer getReq_AmountMobile()
	{
		return getReq_AmountMobile(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_AmountMobile
	 */
	public final java.lang.Integer getReq_AmountMobile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Req_AmountMobile.toString());
	}

	/**
	 * Set value of Req_AmountMobile
	 * @param req_amountmobile
	 */
	public final void setReq_AmountMobile(java.lang.Integer req_amountmobile)
	{
		setReq_AmountMobile(getContext(), req_amountmobile);
	}

	/**
	 * Set value of Req_AmountMobile
	 * @param context
	 * @param req_amountmobile
	 */
	public final void setReq_AmountMobile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer req_amountmobile)
	{
		getMendixObject().setValue(context, MemberNames.Req_AmountMobile.toString(), req_amountmobile);
	}

	/**
	 * @return value of Req_Currency
	 */
	public final java.lang.String getReq_Currency()
	{
		return getReq_Currency(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_Currency
	 */
	public final java.lang.String getReq_Currency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_Currency.toString());
	}

	/**
	 * Set value of Req_Currency
	 * @param req_currency
	 */
	public final void setReq_Currency(java.lang.String req_currency)
	{
		setReq_Currency(getContext(), req_currency);
	}

	/**
	 * Set value of Req_Currency
	 * @param context
	 * @param req_currency
	 */
	public final void setReq_Currency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_currency)
	{
		getMendixObject().setValue(context, MemberNames.Req_Currency.toString(), req_currency);
	}

	/**
	 * @return value of Req_ProdDesc
	 */
	public final java.lang.String getReq_ProdDesc()
	{
		return getReq_ProdDesc(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_ProdDesc
	 */
	public final java.lang.String getReq_ProdDesc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_ProdDesc.toString());
	}

	/**
	 * Set value of Req_ProdDesc
	 * @param req_proddesc
	 */
	public final void setReq_ProdDesc(java.lang.String req_proddesc)
	{
		setReq_ProdDesc(getContext(), req_proddesc);
	}

	/**
	 * Set value of Req_ProdDesc
	 * @param context
	 * @param req_proddesc
	 */
	public final void setReq_ProdDesc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_proddesc)
	{
		getMendixObject().setValue(context, MemberNames.Req_ProdDesc.toString(), req_proddesc);
	}

	/**
	 * @return value of Req_UserName
	 */
	public final java.lang.String getReq_UserName()
	{
		return getReq_UserName(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_UserName
	 */
	public final java.lang.String getReq_UserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_UserName.toString());
	}

	/**
	 * Set value of Req_UserName
	 * @param req_username
	 */
	public final void setReq_UserName(java.lang.String req_username)
	{
		setReq_UserName(getContext(), req_username);
	}

	/**
	 * Set value of Req_UserName
	 * @param context
	 * @param req_username
	 */
	public final void setReq_UserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_username)
	{
		getMendixObject().setValue(context, MemberNames.Req_UserName.toString(), req_username);
	}

	/**
	 * @return value of Req_UserEmail
	 */
	public final java.lang.String getReq_UserEmail()
	{
		return getReq_UserEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_UserEmail
	 */
	public final java.lang.String getReq_UserEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_UserEmail.toString());
	}

	/**
	 * Set value of Req_UserEmail
	 * @param req_useremail
	 */
	public final void setReq_UserEmail(java.lang.String req_useremail)
	{
		setReq_UserEmail(getContext(), req_useremail);
	}

	/**
	 * Set value of Req_UserEmail
	 * @param context
	 * @param req_useremail
	 */
	public final void setReq_UserEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_useremail)
	{
		getMendixObject().setValue(context, MemberNames.Req_UserEmail.toString(), req_useremail);
	}

	/**
	 * @return value of Req_UserContact
	 */
	public final java.lang.String getReq_UserContact()
	{
		return getReq_UserContact(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_UserContact
	 */
	public final java.lang.String getReq_UserContact(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_UserContact.toString());
	}

	/**
	 * Set value of Req_UserContact
	 * @param req_usercontact
	 */
	public final void setReq_UserContact(java.lang.String req_usercontact)
	{
		setReq_UserContact(getContext(), req_usercontact);
	}

	/**
	 * Set value of Req_UserContact
	 * @param context
	 * @param req_usercontact
	 */
	public final void setReq_UserContact(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_usercontact)
	{
		getMendixObject().setValue(context, MemberNames.Req_UserContact.toString(), req_usercontact);
	}

	/**
	 * @return value of Req_Remark
	 */
	public final java.lang.String getReq_Remark()
	{
		return getReq_Remark(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_Remark
	 */
	public final java.lang.String getReq_Remark(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_Remark.toString());
	}

	/**
	 * Set value of Req_Remark
	 * @param req_remark
	 */
	public final void setReq_Remark(java.lang.String req_remark)
	{
		setReq_Remark(getContext(), req_remark);
	}

	/**
	 * Set value of Req_Remark
	 * @param context
	 * @param req_remark
	 */
	public final void setReq_Remark(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_remark)
	{
		getMendixObject().setValue(context, MemberNames.Req_Remark.toString(), req_remark);
	}

	/**
	 * @return value of Req_Lang
	 */
	public final java.lang.String getReq_Lang()
	{
		return getReq_Lang(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_Lang
	 */
	public final java.lang.String getReq_Lang(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_Lang.toString());
	}

	/**
	 * Set value of Req_Lang
	 * @param req_lang
	 */
	public final void setReq_Lang(java.lang.String req_lang)
	{
		setReq_Lang(getContext(), req_lang);
	}

	/**
	 * Set value of Req_Lang
	 * @param context
	 * @param req_lang
	 */
	public final void setReq_Lang(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_lang)
	{
		getMendixObject().setValue(context, MemberNames.Req_Lang.toString(), req_lang);
	}

	/**
	 * @return value of Req_Signature
	 */
	public final java.lang.String getReq_Signature()
	{
		return getReq_Signature(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_Signature
	 */
	public final java.lang.String getReq_Signature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_Signature.toString());
	}

	/**
	 * Set value of Req_Signature
	 * @param req_signature
	 */
	public final void setReq_Signature(java.lang.String req_signature)
	{
		setReq_Signature(getContext(), req_signature);
	}

	/**
	 * Set value of Req_Signature
	 * @param context
	 * @param req_signature
	 */
	public final void setReq_Signature(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_signature)
	{
		getMendixObject().setValue(context, MemberNames.Req_Signature.toString(), req_signature);
	}

	/**
	 * @return value of Req_ResponseURL
	 */
	public final java.lang.String getReq_ResponseURL()
	{
		return getReq_ResponseURL(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_ResponseURL
	 */
	public final java.lang.String getReq_ResponseURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_ResponseURL.toString());
	}

	/**
	 * Set value of Req_ResponseURL
	 * @param req_responseurl
	 */
	public final void setReq_ResponseURL(java.lang.String req_responseurl)
	{
		setReq_ResponseURL(getContext(), req_responseurl);
	}

	/**
	 * Set value of Req_ResponseURL
	 * @param context
	 * @param req_responseurl
	 */
	public final void setReq_ResponseURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_responseurl)
	{
		getMendixObject().setValue(context, MemberNames.Req_ResponseURL.toString(), req_responseurl);
	}

	/**
	 * @return value of Req_BackendURL
	 */
	public final java.lang.String getReq_BackendURL()
	{
		return getReq_BackendURL(getContext());
	}

	/**
	 * @param context
	 * @return value of Req_BackendURL
	 */
	public final java.lang.String getReq_BackendURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Req_BackendURL.toString());
	}

	/**
	 * Set value of Req_BackendURL
	 * @param req_backendurl
	 */
	public final void setReq_BackendURL(java.lang.String req_backendurl)
	{
		setReq_BackendURL(getContext(), req_backendurl);
	}

	/**
	 * Set value of Req_BackendURL
	 * @param context
	 * @param req_backendurl
	 */
	public final void setReq_BackendURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String req_backendurl)
	{
		getMendixObject().setValue(context, MemberNames.Req_BackendURL.toString(), req_backendurl);
	}

	/**
	 * @return value of Res_MerchantCode
	 */
	public final java.lang.String getRes_MerchantCode()
	{
		return getRes_MerchantCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_MerchantCode
	 */
	public final java.lang.String getRes_MerchantCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_MerchantCode.toString());
	}

	/**
	 * Set value of Res_MerchantCode
	 * @param res_merchantcode
	 */
	public final void setRes_MerchantCode(java.lang.String res_merchantcode)
	{
		setRes_MerchantCode(getContext(), res_merchantcode);
	}

	/**
	 * Set value of Res_MerchantCode
	 * @param context
	 * @param res_merchantcode
	 */
	public final void setRes_MerchantCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_merchantcode)
	{
		getMendixObject().setValue(context, MemberNames.Res_MerchantCode.toString(), res_merchantcode);
	}

	/**
	 * @return value of Res_PaymentId
	 */
	public final java.lang.String getRes_PaymentId()
	{
		return getRes_PaymentId(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_PaymentId
	 */
	public final java.lang.String getRes_PaymentId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_PaymentId.toString());
	}

	/**
	 * Set value of Res_PaymentId
	 * @param res_paymentid
	 */
	public final void setRes_PaymentId(java.lang.String res_paymentid)
	{
		setRes_PaymentId(getContext(), res_paymentid);
	}

	/**
	 * Set value of Res_PaymentId
	 * @param context
	 * @param res_paymentid
	 */
	public final void setRes_PaymentId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_paymentid)
	{
		getMendixObject().setValue(context, MemberNames.Res_PaymentId.toString(), res_paymentid);
	}

	/**
	 * @return value of Res_RefNo
	 */
	public final java.lang.String getRes_RefNo()
	{
		return getRes_RefNo(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_RefNo
	 */
	public final java.lang.String getRes_RefNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_RefNo.toString());
	}

	/**
	 * Set value of Res_RefNo
	 * @param res_refno
	 */
	public final void setRes_RefNo(java.lang.String res_refno)
	{
		setRes_RefNo(getContext(), res_refno);
	}

	/**
	 * Set value of Res_RefNo
	 * @param context
	 * @param res_refno
	 */
	public final void setRes_RefNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_refno)
	{
		getMendixObject().setValue(context, MemberNames.Res_RefNo.toString(), res_refno);
	}

	/**
	 * @return value of Res_Amount
	 */
	public final java.lang.String getRes_Amount()
	{
		return getRes_Amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_Amount
	 */
	public final java.lang.String getRes_Amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_Amount.toString());
	}

	/**
	 * Set value of Res_Amount
	 * @param res_amount
	 */
	public final void setRes_Amount(java.lang.String res_amount)
	{
		setRes_Amount(getContext(), res_amount);
	}

	/**
	 * Set value of Res_Amount
	 * @param context
	 * @param res_amount
	 */
	public final void setRes_Amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_amount)
	{
		getMendixObject().setValue(context, MemberNames.Res_Amount.toString(), res_amount);
	}

	/**
	 * @return value of Res_Currency
	 */
	public final java.lang.String getRes_Currency()
	{
		return getRes_Currency(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_Currency
	 */
	public final java.lang.String getRes_Currency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_Currency.toString());
	}

	/**
	 * Set value of Res_Currency
	 * @param res_currency
	 */
	public final void setRes_Currency(java.lang.String res_currency)
	{
		setRes_Currency(getContext(), res_currency);
	}

	/**
	 * Set value of Res_Currency
	 * @param context
	 * @param res_currency
	 */
	public final void setRes_Currency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_currency)
	{
		getMendixObject().setValue(context, MemberNames.Res_Currency.toString(), res_currency);
	}

	/**
	 * @return value of Res_Remark
	 */
	public final java.lang.String getRes_Remark()
	{
		return getRes_Remark(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_Remark
	 */
	public final java.lang.String getRes_Remark(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_Remark.toString());
	}

	/**
	 * Set value of Res_Remark
	 * @param res_remark
	 */
	public final void setRes_Remark(java.lang.String res_remark)
	{
		setRes_Remark(getContext(), res_remark);
	}

	/**
	 * Set value of Res_Remark
	 * @param context
	 * @param res_remark
	 */
	public final void setRes_Remark(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_remark)
	{
		getMendixObject().setValue(context, MemberNames.Res_Remark.toString(), res_remark);
	}

	/**
	 * @return value of Res_TransId
	 */
	public final java.lang.String getRes_TransId()
	{
		return getRes_TransId(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_TransId
	 */
	public final java.lang.String getRes_TransId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_TransId.toString());
	}

	/**
	 * Set value of Res_TransId
	 * @param res_transid
	 */
	public final void setRes_TransId(java.lang.String res_transid)
	{
		setRes_TransId(getContext(), res_transid);
	}

	/**
	 * Set value of Res_TransId
	 * @param context
	 * @param res_transid
	 */
	public final void setRes_TransId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_transid)
	{
		getMendixObject().setValue(context, MemberNames.Res_TransId.toString(), res_transid);
	}

	/**
	 * @return value of Res_AuthCode
	 */
	public final java.lang.String getRes_AuthCode()
	{
		return getRes_AuthCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_AuthCode
	 */
	public final java.lang.String getRes_AuthCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_AuthCode.toString());
	}

	/**
	 * Set value of Res_AuthCode
	 * @param res_authcode
	 */
	public final void setRes_AuthCode(java.lang.String res_authcode)
	{
		setRes_AuthCode(getContext(), res_authcode);
	}

	/**
	 * Set value of Res_AuthCode
	 * @param context
	 * @param res_authcode
	 */
	public final void setRes_AuthCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_authcode)
	{
		getMendixObject().setValue(context, MemberNames.Res_AuthCode.toString(), res_authcode);
	}

	/**
	 * @return value of Res_Status
	 */
	public final java.lang.String getRes_Status()
	{
		return getRes_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_Status
	 */
	public final java.lang.String getRes_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_Status.toString());
	}

	/**
	 * Set value of Res_Status
	 * @param res_status
	 */
	public final void setRes_Status(java.lang.String res_status)
	{
		setRes_Status(getContext(), res_status);
	}

	/**
	 * Set value of Res_Status
	 * @param context
	 * @param res_status
	 */
	public final void setRes_Status(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_status)
	{
		getMendixObject().setValue(context, MemberNames.Res_Status.toString(), res_status);
	}

	/**
	 * @return value of Res_ErrDesc
	 */
	public final java.lang.String getRes_ErrDesc()
	{
		return getRes_ErrDesc(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_ErrDesc
	 */
	public final java.lang.String getRes_ErrDesc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_ErrDesc.toString());
	}

	/**
	 * Set value of Res_ErrDesc
	 * @param res_errdesc
	 */
	public final void setRes_ErrDesc(java.lang.String res_errdesc)
	{
		setRes_ErrDesc(getContext(), res_errdesc);
	}

	/**
	 * Set value of Res_ErrDesc
	 * @param context
	 * @param res_errdesc
	 */
	public final void setRes_ErrDesc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_errdesc)
	{
		getMendixObject().setValue(context, MemberNames.Res_ErrDesc.toString(), res_errdesc);
	}

	/**
	 * @return value of Res_Signature
	 */
	public final java.lang.String getRes_Signature()
	{
		return getRes_Signature(getContext());
	}

	/**
	 * @param context
	 * @return value of Res_Signature
	 */
	public final java.lang.String getRes_Signature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Res_Signature.toString());
	}

	/**
	 * Set value of Res_Signature
	 * @param res_signature
	 */
	public final void setRes_Signature(java.lang.String res_signature)
	{
		setRes_Signature(getContext(), res_signature);
	}

	/**
	 * Set value of Res_Signature
	 * @param context
	 * @param res_signature
	 */
	public final void setRes_Signature(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String res_signature)
	{
		getMendixObject().setValue(context, MemberNames.Res_Signature.toString(), res_signature);
	}

	/**
	 * Set value of PaymentResponseStatus
	 * @param paymentresponsestatus
	 */
	public final paymentinterfaces.proxies.PaymentResponseStatus getPaymentResponseStatus()
	{
		return getPaymentResponseStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentResponseStatus
	 */
	public final paymentinterfaces.proxies.PaymentResponseStatus getPaymentResponseStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PaymentResponseStatus.toString());
		if (obj == null)
			return null;

		return paymentinterfaces.proxies.PaymentResponseStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PaymentResponseStatus
	 * @param paymentresponsestatus
	 */
	public final void setPaymentResponseStatus(paymentinterfaces.proxies.PaymentResponseStatus paymentresponsestatus)
	{
		setPaymentResponseStatus(getContext(), paymentresponsestatus);
	}

	/**
	 * Set value of PaymentResponseStatus
	 * @param context
	 * @param paymentresponsestatus
	 */
	public final void setPaymentResponseStatus(com.mendix.systemwideinterfaces.core.IContext context, paymentinterfaces.proxies.PaymentResponseStatus paymentresponsestatus)
	{
		if (paymentresponsestatus != null)
			getMendixObject().setValue(context, MemberNames.PaymentResponseStatus.toString(), paymentresponsestatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.PaymentResponseStatus.toString(), null);
	}

	/**
	 * @return value of IsCallbackProcessed
	 */
	public final java.lang.Boolean getIsCallbackProcessed()
	{
		return getIsCallbackProcessed(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCallbackProcessed
	 */
	public final java.lang.Boolean getIsCallbackProcessed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCallbackProcessed.toString());
	}

	/**
	 * Set value of IsCallbackProcessed
	 * @param iscallbackprocessed
	 */
	public final void setIsCallbackProcessed(java.lang.Boolean iscallbackprocessed)
	{
		setIsCallbackProcessed(getContext(), iscallbackprocessed);
	}

	/**
	 * Set value of IsCallbackProcessed
	 * @param context
	 * @param iscallbackprocessed
	 */
	public final void setIsCallbackProcessed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscallbackprocessed)
	{
		getMendixObject().setValue(context, MemberNames.IsCallbackProcessed.toString(), iscallbackprocessed);
	}

	/**
	 * @return value of IPay88Transaction_PaymentRedirect
	 */
	public final paymentinterfaces.proxies.PaymentRedirect getIPay88Transaction_PaymentRedirect() throws com.mendix.core.CoreException
	{
		return getIPay88Transaction_PaymentRedirect(getContext());
	}

	/**
	 * @param context
	 * @return value of IPay88Transaction_PaymentRedirect
	 */
	public final paymentinterfaces.proxies.PaymentRedirect getIPay88Transaction_PaymentRedirect(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentinterfaces.proxies.PaymentRedirect result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IPay88Transaction_PaymentRedirect.toString());
		if (identifier != null)
			result = paymentinterfaces.proxies.PaymentRedirect.load(context, identifier);
		return result;
	}

	/**
	 * Set value of IPay88Transaction_PaymentRedirect
	 * @param ipay88transaction_paymentredirect
	 */
	public final void setIPay88Transaction_PaymentRedirect(paymentinterfaces.proxies.PaymentRedirect ipay88transaction_paymentredirect)
	{
		setIPay88Transaction_PaymentRedirect(getContext(), ipay88transaction_paymentredirect);
	}

	/**
	 * Set value of IPay88Transaction_PaymentRedirect
	 * @param context
	 * @param ipay88transaction_paymentredirect
	 */
	public final void setIPay88Transaction_PaymentRedirect(com.mendix.systemwideinterfaces.core.IContext context, paymentinterfaces.proxies.PaymentRedirect ipay88transaction_paymentredirect)
	{
		if (ipay88transaction_paymentredirect == null)
			getMendixObject().setValue(context, MemberNames.IPay88Transaction_PaymentRedirect.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.IPay88Transaction_PaymentRedirect.toString(), ipay88transaction_paymentredirect.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return iPay88TransactionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentinterfaces.proxies.IPay88Transaction that = (paymentinterfaces.proxies.IPay88Transaction) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PaymentInterfaces.IPay88Transaction";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
