// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package paymentinterfaces.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.google.common.hash.Hashing;
import java.security.*;
import sun.misc.BASE64Encoder;
import java.io.*;

public class iPay_SHA1_Encode extends CustomJavaAction<java.lang.String>
{
	private java.lang.String stringToHash;

	public iPay_SHA1_Encode(IContext context, java.lang.String stringToHash)
	{
		super(context);
		this.stringToHash = stringToHash;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageDigest md;
		try 
		{
			md = MessageDigest.getInstance("SHA");
			md.update(this.stringToHash.getBytes("UTF-8")); // step 3
			byte raw[] = md.digest(); // step 4
			String hash = (new BASE64Encoder()).encode(raw); // step 5
			return hash; // step 6
		}	 
		catch (NoSuchAlgorithmException e) 
		{
		} 
		catch (java.io.UnsupportedEncodingException e) 
		{
		}
    return null;
		//return Hashing.sha1().hashString(this.stringToHash).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "iPay_SHA1_Encode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
